server:
  port: 9090
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://sso.example.com:9080/auth/realms/heroes/protocol/openid-connect/certs

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.security.oauth2: DEBUG